In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("========")

144
170
164
167
177


In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [5]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [6]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [8]:
np.random.randint(60,101,size=(50, 5))

array([[ 61,  62, 100,  94,  61],
       [ 92,  69,  98,  65,  63],
       [ 88,  91,  70,  88,  94],
       [ 97,  65,  78,  77,  69],
       [ 63,  62,  84,  91,  97],
       [ 76,  76, 100,  98,  60],
       [ 94,  65,  95,  76,  64],
       [ 71,  81,  97,  74,  83],
       [ 85,  64,  63,  67,  95],
       [ 93,  85,  96,  79,  98],
       [ 71,  77,  83,  95,  62],
       [ 64,  77,  61,  75,  92],
       [ 85,  86,  61,  63,  60],
       [ 65,  63,  99,  68,  62],
       [ 89,  84,  84,  76,  90],
       [ 99, 100,  65,  82,  74],
       [ 76,  96,  66,  75,  97],
       [ 62,  88,  82,  98,  80],
       [ 98,  87,  99,  90,  91],
       [ 83,  63, 100,  65,  67],
       [100,  60,  86,  68,  77],
       [100,  61,  70,  96,  65],
       [ 64,  79,  75,  74,  95],
       [ 76,  98,  66,  86,  80],
       [ 82,  85,  86,  80,  63],
       [ 86,  86,  90,  87,  83],
       [ 75,  92,  64, 100,  76],
       [ 93,  96,  66,  64, 100],
       [ 92,  98,  85,  72,  77],
       [ 71,  